config/routes.rb
Tennis::Application.routes.draw do
  resources :costs

  resources :match_costs

  resources :terms

  resources :kitty_trans

  resources :matches

  resources :players

  root 'players#index'

end

app/models/match_cost.rb
class MatchCost < ActiveRecord::Base
has_many :Matchs
has_one :Cost
belongs_to :match

validates_presence_of :cost_code
validates_presence_of :mID
end

app/controllers/match_costs_controller.rb
class MatchCostsController < ApplicationController
  before_action :set_match_cost, only: [:show, :edit, :update, :destroy]

  # GET /match_costs
  # GET /match_costs.json
  def index
    @match_costs = MatchCost.all
  end

  # GET /match_costs/1
  # GET /match_costs/1.json
  def show
  end

  # GET /match_costs/new
  def new
    @match_cost = MatchCost.new
  end

  # GET /match_costs/1/edit
  def edit
  end

  # POST /match_costs
  # POST /match_costs.json
  def create
    @match_cost = MatchCost.new(match_cost_params)

    respond_to do |format|
      if @match_cost.save
        format.html { redirect_to @match_cost, notice: 'Match cost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match_cost }
      else
        format.html { render action: 'new' }
        format.json { render json: @match_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /match_costs/1
  # PATCH/PUT /match_costs/1.json
  def update
    respond_to do |format|
      if @match_cost.update(match_cost_params)
        format.html { redirect_to @match_cost, notice: 'Match cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_costs/1
  # DELETE /match_costs/1.json
  def destroy
    @match_cost.destroy
    respond_to do |format|
      format.html { redirect_to match_costs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_cost
      @match_cost = MatchCost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_cost_params
      params.require(:match_cost).permit(:cost_code, :mID)
    end
end

app/helpers/match_costs_helper.rb
module MatchCostsHelper
end

app/views/match_costs/_form.html.erb
<%= form_for(@match_cost) do |f| %>
  <% if @match_cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match_cost.errors.count, "error") %> prohibited this match_cost from being saved:</h2>

      <ul>
      <% @match_cost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_code %><br>
    <%= f.number_field :cost_code %>
  </div>
  <div class="field">
    <%= f.label :mID %><br>
    <%= f.number_field :mID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/match_costs/edit.html.erb
<h1>Editing match_cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @match_cost %> |
<%= link_to 'Back', match_costs_path %>

app/views/match_costs/index.html.erb
<h1>Listing match_costs</h1>

<table>
  <thead>
    <tr>
      <th>Cost code</th>
      <th>Mid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @match_costs.each do |match_cost| %>
      <tr>
        <td><%= match_cost.cost_code %></td>
        <td><%= match_cost.mID %></td>
        <td><%= link_to 'Show', match_cost %></td>
        <td><%= link_to 'Edit', edit_match_cost_path(match_cost) %></td>
        <td><%= link_to 'Destroy', match_cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match cost', new_match_cost_path %>

app/views/match_costs/new.html.erb
<h1>New match_cost</h1>

<%= render 'form' %>

<%= link_to 'Back', match_costs_path %>

app/views/match_costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost code:</strong>
  <%= @match_cost.cost_code %>
</p>

<p>
  <strong>Mid:</strong>
  <%= @match_cost.mID %>
</p>

<%= link_to 'Edit', edit_match_cost_path(@match_cost) %> |
<%= link_to 'Back', match_costs_path %>