config/routes.rb
Tennis::Application.routes.draw do
  resources :costs

  resources :match_costs

  resources :terms

  resources :kitty_trans

  resources :matches

  resources :players

  root 'players#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
has_many :KittyTrans
has_many :Matchs

validates_presence_of :first
validates_presence_of :last
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first, :last, :full_charge, :play_singles, :pref9, :only9, :active)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :full_charge %><br>
    <%= f.check_box :full_charge %>
  </div>
  <div class="field">
    <%= f.label :play_singles %><br>
    <%= f.check_box :play_singles %>
  </div>
  <div class="field">
    <%= f.label :pref9 %><br>
    <%= f.check_box :pref9 %>
  </div>
  <div class="field">
    <%= f.label :only9 %><br>
    <%= f.check_box :only9 %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h2>Welcome to Monday Night Tennis</h2>

<br>

<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Full charge</th>
      <th>Play singles</th>
      <th>Pref9</th>
      <th>Only9</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.first %></td>
        <td><%= player.last %></td>
        <td><%= player.full_charge %></td>
        <td><%= player.play_singles %></td>
        <td><%= player.pref9 %></td>
        <td><%= player.only9 %></td>
        <td><%= player.active %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

<br>

<h3>Who will play tonight?</h3>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @player.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @player.last %>
</p>

<p>
  <strong>Full charge:</strong>
  <%= @player.full_charge %>
</p>

<p>
  <strong>Play singles:</strong>
  <%= @player.play_singles %>
</p>

<p>
  <strong>Pref9:</strong>
  <%= @player.pref9 %>
</p>

<p>
  <strong>Only9:</strong>
  <%= @player.only9 %>
</p>

<p>
  <strong>Active:</strong>
  <%= @player.active %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>