config/routes.rb
Tennis::Application.routes.draw do
  resources :costs

  resources :match_costs

  resources :terms

  resources :kitty_trans

  resources :matches

  resources :players

  root 'players#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
has_many :KittyTrans

validates_presence_of :t11
validates_presence_of :t21
validates_presence_of :match_date
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:t11, :t12, :t1s, :t21, :t22, :t2s, :match_date, :doubles)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :t11 %><br>
    <%= f.number_field :t11 %>
  </div>
  <div class="field">
    <%= f.label :t12 %><br>
    <%= f.number_field :t12 %>
  </div>
  <div class="field">
    <%= f.label :t1s %><br>
    <%= f.number_field :t1s %>
  </div>
  <div class="field">
    <%= f.label :t21 %><br>
    <%= f.number_field :t21 %>
  </div>
  <div class="field">
    <%= f.label :t22 %><br>
    <%= f.number_field :t22 %>
  </div>
  <div class="field">
    <%= f.label :t2s %><br>
    <%= f.number_field :t2s %>
  </div>
  <div class="field">
    <%= f.label :match_date %><br>
    <%= f.datetime_select :match_date %>
  </div>
  <div class="field">
    <%= f.label :doubles %><br>
    <%= f.check_box :doubles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <thead>
    <tr>
      <th>T11</th>
      <th>T12</th>
      <th>T1s</th>
      <th>T21</th>
      <th>T22</th>
      <th>T2s</th>
      <th>Match date</th>
      <th>Doubles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.t11 %></td>
        <td><%= match.t12 %></td>
        <td><%= match.t1s %></td>
        <td><%= match.t21 %></td>
        <td><%= match.t22 %></td>
        <td><%= match.t2s %></td>
        <td><%= match.match_date %></td>
        <td><%= match.doubles %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>T11:</strong>
  <%= @match.t11 %>
</p>

<p>
  <strong>T12:</strong>
  <%= @match.t12 %>
</p>

<p>
  <strong>T1s:</strong>
  <%= @match.t1s %>
</p>

<p>
  <strong>T21:</strong>
  <%= @match.t21 %>
</p>

<p>
  <strong>T22:</strong>
  <%= @match.t22 %>
</p>

<p>
  <strong>T2s:</strong>
  <%= @match.t2s %>
</p>

<p>
  <strong>Match date:</strong>
  <%= @match.match_date %>
</p>

<p>
  <strong>Doubles:</strong>
  <%= @match.doubles %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>